# Generated by Django 3.2 on 2021-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='')),
                ('thumbnail_img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
