# Generated by Django 3.2 on 2021-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
