# Generated by Django 3.2.3 on 2021-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_date_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='more_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
