# Generated by Django 4.2.1 on 2023-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_category_project_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
