# Generated by Django 4.2.15 on 2024-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='group',
            field=models.CharField(choices=[('FR', 'Frontend'), ('BA', 'Backend'), ('MS', 'Miscelaneous')], default='MS', max_length=2),
        ),
    ]
