# Generated by Django 4.2.15 on 2025-02-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_tool_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='group',
            field=models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('FS', 'Fullstack'), ('GD', 'Game Development'), ('DC', 'DevOps and Cloud Computing'), ('DB', 'Databases')], default='FS', max_length=2),
        ),
    ]
