# Generated by Django 4.2.11 on 2024-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=3000)),
                ('about_description', models.TextField()),
                ('about_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
