# Generated by Django 4.2.11 on 2024-04-03 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_contentmodel_typewriter_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='typewriter_texts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
